import os
import sys
import importlib
import traceback
import logging

logger = logging.getLogger(__name__)

class SelfEvolutionEngine:
    """
    Dynamic Plugin Architecture & Hot-Reloading System.
    Allows the AI to write, compile, and execute its own Python tools (Skills) live without restarting.
    """
    def __init__(self, memory):
        self.memory = memory
        # Create a dedicated 'skills' folder inside the agent directory
        self.skills_dir = os.path.join(os.path.dirname(__file__), "skills")
        os.makedirs(self.skills_dir, exist_ok=True)
        
        # Add the folder to sys.path so importlib can find the modules
        if self.skills_dir not in sys.path:
            sys.path.insert(0, self.skills_dir)
            
    def create_and_load_skill(self, skill_name: str, python_code: str) -> dict:
        """Saves, syntax-checks, and hot-reloads a new Python skill."""
        skill_name = skill_name.replace(" ", "_").replace("-", "_").lower()
        if not skill_name.isidentifier():
            return {"success": False, "error": f"Invalid skill name '{skill_name}'. Must be a valid Python identifier."}
            
        file_path = os.path.join(self.skills_dir, f"{skill_name}.py")
        
        # 1. Save the code generated by the AI
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(python_code)
        except Exception as e:
            return {"success": False, "error": f"Failed to save skill file: {e}"}
            
        # 2. Syntax Check (Compile phase without execution)
        try:
            compile(python_code, file_path, 'exec')
        except SyntaxError as e:
            os.remove(file_path) # Delete broken code
            error_msg = f"SyntaxError in generated code at line {e.lineno}: {e.msg}"
            self.memory.log_error({"action": "create_skill", "name": skill_name}, error_msg, "Compile Phase")
            return {"success": False, "error": error_msg}
            
        # 3. Dynamic Hot-Reloading
        try:
            if skill_name in sys.modules:
                # If skill exists, we reload it to apply the new code!
                module = importlib.reload(sys.modules[skill_name])
            else:
                module = importlib.import_module(skill_name)
                
            # Contract Verification: The skill must export a `run` function
            if not hasattr(module, 'run'):
                os.remove(file_path)
                if skill_name in sys.modules:
                    del sys.modules[skill_name]
                return {"success": False, "error": "Skill module must define a 'def run(**kwargs):' function."}
                
            # 4. Save the Evolution into Mem0's "Brain"
            success_msg = f"I have successfully learned a new skill. I can now '{skill_name}'."
            self.memory.learn_user_preference(success_msg)
            
            return {
                "success": True, 
                "message": f"Skill '{skill_name}' successfully learned and hot-reloaded! You can now use execute_skill."
            }
            
        except Exception as e:
            # Revert on failure
            if os.path.exists(file_path):
                os.remove(file_path)
            if skill_name in sys.modules:
                del sys.modules[skill_name]
            error_msg = f"Failed to import/reload skill: {str(e)}\n{traceback.format_exc()}"
            self.memory.log_error({"action": "create_skill", "name": skill_name}, error_msg, "Import Phase")
            return {"success": False, "error": error_msg}
            
    def execute_skill(self, skill_name: str, params: dict = None) -> dict:
        """Executes a previously learned skill."""
        if params is None:
            params = {}
            
        try:
            if skill_name not in sys.modules:
                module = importlib.import_module(skill_name)
            else:
                module = sys.modules[skill_name]
                
            # Execute the skill
            result = module.run(**params)
            return {"success": True, "result": str(result)}
            
        except Exception as e:
            error_msg = f"Skill execution failed: {str(e)}\n{traceback.format_exc()}"
            self.memory.log_error({"action": "execute_skill", "name": skill_name}, error_msg, "Run Phase")
            return {"success": False, "error": error_msg}
